theme: jekyll-theme-cayman
title-img: /images/HibiscusLogoFlush.png
title: Amy Rideg, MA, MFT
description: Registered Associate Marriage and Family Therapist in Santa Barbara, CA | AMFT #97827 | Supervised by Gary G. Linker, PhD, LMFT
